### ISSUE TITLE
跨页删除展示有歧义

### ISSUE THREAD

**Issue by cMing1997** [any86/crud-vue#1]
如果只支持当前页删除，但是选中之后切换分页，删除按钮数字没有重置
如果是支持跨页删除，那选中之后，切换分页再切回来，应该是有会选选中的，但是现在两种情况都有问题
![image](https://user-images.githubusercontent.com/40878104/182987082-d318b20d-4fa1-43d9-b6f5-578020ff3521.png)

**Comment by any86** [comment]
感谢反馈, 我一会改下.

**Comment by any86** [comment]
已修复: https://v-curd.vercel.app/ , 现在是每次翻页清空上一页的选择
